services:
  app:
    build:
      context: ./
      dockerfile: php/Dockerfile
    container_name: example-app
    restart: always
    volumes:
      - "../src:/var/www"
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"

  server:
    image: nginx:alpine
    container_name: example-server
    restart: always
    ports:
      - "9000:80"
    volumes:
      - "../src:/var/www"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      
  database:
    image: mariadb:latest
    container_name: example-database
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - "./mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    command: ['--sql_mode=']
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      TZ: ${DB_TIMEZONE}

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: example-phpmyadmin
    restart: always
    ports:
      - "9001:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 100M